/*******************************************************************************
* File Name:   main.c
*
* Description: UART Echo Example using polling mode for Traveo T2G.
*******************************************************************************/

#include "cy_scb_uart.h"
#include "cybsp.h"                 // Board Support Package header
#include "cycfg_peripherals.h"     // Peripheral configuration generated by Device Configurator

/* UART context structure required by PDL functions */
cy_stc_scb_uart_context_t UART_context;


/* Variable to store a received character */
uint8_t rx_data;

int main(void)
{
    cy_rslt_t result;  // Variable to hold function return values

    // Initialize the board and system peripherals
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        // Halt the CPU if initialization failed
        CY_ASSERT(0);
    }

    // Initialize the UART peripheral with the configuration generated by Device Configurator
    Cy_SCB_UART_Init(UART_HW, &UART_config, &UART_context);

    // Enable the UART block
    Cy_SCB_UART_Enable(UART_HW);

    // Send ANSI escape sequence to clear the terminal and move cursor to the top-left corner
    Cy_SCB_UART_PutString(UART_HW, "\x1b[2J\x1b[;H");

    // Print welcome message and configuration info
    Cy_SCB_UART_PutString(UART_HW, "=========================================\r\n");
    Cy_SCB_UART_PutString(UART_HW, "         Traveo T2G UART Echo Demo       \r\n");
    Cy_SCB_UART_PutString(UART_HW, "=========================================\r\n");
    Cy_SCB_UART_PutString(UART_HW, " UART Mode : Polling\r\n");
    Cy_SCB_UART_PutString(UART_HW, " RX Pin    : P0.0\r\n");
    Cy_SCB_UART_PutString(UART_HW, " TX Pin    : P0.1\r\n");
    Cy_SCB_UART_PutString(UART_HW, " Baudrate  : 115200 bps (8N1)\r\n");
    Cy_SCB_UART_PutString(UART_HW, "-----------------------------------------\r\n");
    Cy_SCB_UART_PutString(UART_HW, " >> Type any key and it will echo back!\r\n\r\n");

    // Enable global interrupts (not necessary for polling mode, but a good practice)
    __enable_irq();

    // Infinite loop for polling UART RX
    for (;;)
    {
        // Check if there is at least one character in the RX FIFO
        if (Cy_SCB_UART_GetNumInRxFifo(UART_HW) > 0)
        {
            // Read the received character
            rx_data = Cy_SCB_UART_Get(UART_HW);

            // Send the same character back to the terminal (echo)
            Cy_SCB_UART_Put(UART_HW, rx_data);
        }
    }
}

/* [] END OF FILE */
