/*******************************************************************************
 * File Name:   main.c
 *
 * Description:
 * Example 09 – SPI with MAX6675 Thermocouple Sensor:
 * This example communicates with the MAX6675 thermocouple sensor using SPI
 * and prints the temperature in Celsius to the UART terminal using retarget-io.
 *
 * The SPI reads two bytes of data and calculates the temperature in real-time.
 *
 * - SPI MISO: P13.0
 * - SPI MOSI: P13.1 (not used by MAX6675, but required for full SPI config)
 * - SPI CLK:  P13.2
 * - CS (Chip Select): P13.6 (controlled manually via GPIO)
 * - UART TX/RX: Used for printf output via Retarget I/O
 * - SPI Clock: 100 kbps
 *
 * Related Document: See README.md
 *
 ********************************************************************************
 * Author: Rodrigo Teixeira
 *******************************************************************************/

/*******************************************************************************
 * Header Files
 *******************************************************************************/

#include "cybsp.h"          // Board Support Package for Cypress devices
#include "cy_retarget_io.h" // For retargeting I/O to debug UART

// Function prototypes for MAX6675 temperature sensor
void max6675_init(void);
float max6675_read_temperature(void);

cy_stc_scb_spi_context_t spi_context; // Context for the SPI driver

/*******************************************************************************
 * Function Name: main
 *******************************************************************************
 * Summary:
 *   Main function that initializes the system, reads temperature from the MAX6675
 *   sensor, and prints it to the debug UART.
 *
 * Parameters:
 *   None
 *
 * Return:
 *   int - Default return value for main function
 *******************************************************************************/
int main(void)
{
	cy_rslt_t result; // Variable to store the result of operations

	__enable_irq(); // Enable global interrupts

	// Initialize the Board Support Package (BSP)
	result = cybsp_init();
	CY_ASSERT(result == CY_RSLT_SUCCESS); // Assert if initialization fails

	// Initialize retarget-io to use the debug UART for printf
	result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, 115200);
	CY_ASSERT(result == CY_RSLT_SUCCESS); // Assert if initialization fails

	printf("\x1b[2J\x1b[;H"); // Clear terminal
	printf("=========================================\r\n");
	printf("   Traveo T2G SPI – MAX6675 Temperature   \r\n");
	printf("=========================================\r\n");
	printf(" SPI Clock: 100 kbps\r\n");
	printf(" CS: P13.6 | CLK: P13.2 | MISO: P13.0\r\n");
	printf(" UART Baud: 115200\r\n");
	printf("-----------------------------------------\r\n\r\n");

	// Initialize the MAX6675 temperature sensor
	max6675_init();

	// Main loop to continuously read and print temperature
	for (;;)
	{
		float temperature = max6675_read_temperature(); // Read temperature from MAX6675
		if (temperature < 0)
		{
			printf("Error reading MAX6675 sensor!\n\r"); // Print error if reading fails
		}
		else
		{
			printf("Temperature: %.2f° C\n\r", temperature); // Print temperature value
		}
		Cy_SysLib_Delay(1000); // Delay for 1 second
		
	}
}

/*******************************************************************************
 * Function Name: max6675_init
 *******************************************************************************
 * Summary:
 *   Initializes the SPI interface and configures the Chip Select (CS) pin for
 *   the MAX6675 temperature sensor.
 *
 * Parameters:
 *   None
 *
 * Return:
 *   None
 *******************************************************************************/
void max6675_init(void)
{
	// Disable SPI before initialization
	Cy_SCB_SPI_Disable(SPI_HW, NULL);

	// Initialize SPI with the configuration generated by the Device Configurator
	Cy_SCB_SPI_Init(SPI_HW, &SPI_config, &spi_context);

	// Enable SPI after initialization
	Cy_SCB_SPI_Enable(SPI_HW);

	// Configure the Chip Select (CS) pin as a GPIO
	Cy_GPIO_Pin_FastInit(GPIO_PRT13, 6, CY_GPIO_DM_STRONG, 1, HSIOM_SEL_GPIO);

	// Ensure the CS pin starts in a high state (inactive)
	Cy_GPIO_Write(GPIO_PRT13, 6, 1);
}

/*******************************************************************************
 * Function Name: max6675_read_temperature
 *******************************************************************************
 * Summary:
 *   Reads the temperature from the MAX6675 temperature sensor via SPI.
 *
 * Parameters:
 *   None
 *
 * Return:
 *   float - Temperature in degrees Celsius, or -1.0 if the sensor is disconnected
 *******************************************************************************/
float max6675_read_temperature(void)
{
	uint8_t txBuffer[2] = {0xFF, 0xFF}; // Buffer to send dummy data
	uint8_t rxBuffer[2] = {0};         // Buffer to store received data

	// Activate the CS pin (set to low)
	Cy_GPIO_Write(GPIO_PRT13, 6, 0);

	// Perform SPI transfer
	Cy_SCB_SPI_Write(SPI_HW, txBuffer[0]);    // Send first byte
	while (Cy_SCB_SPI_GetNumInRxFifo(SPI_HW) == 0); // wait until RX FIFO has data
	rxBuffer[0] = Cy_SCB_SPI_Read(SPI_HW);    // Read first byte
	Cy_SCB_SPI_Write(SPI_HW, txBuffer[1]);    // Send second byte
	while (Cy_SCB_SPI_GetNumInRxFifo(SPI_HW) == 0); // wait until RX FIFO has data
	rxBuffer[1] = Cy_SCB_SPI_Read(SPI_HW);    // Read second byte
	while (!Cy_SCB_SPI_IsTxComplete(SPI_HW)); // Wait for transmission to complete

	// Wait until SPI is no longer busy
	while (Cy_SCB_SPI_IsBusBusy(SPI_HW));

	// Deactivate the CS pin (set to high)
	Cy_GPIO_Write(GPIO_PRT13, 6, 1);

	// Combine the two received bytes into a 16-bit value
	uint16_t rawData = (rxBuffer[0] << 8) | rxBuffer[1];

	// Check if the thermocouple is disconnected
	if (rawData & 0x03)
	{
		return -1.0f; // Return -1.0 if the sensor is disconnected
	}

	// Calculate the temperature in degrees Celsius
	float temperature = ((rawData >> 3) & 0x0FFF) * 0.25; // Use only relevant bits
	return temperature;
}
