/*******************************************************************************
* File Name:   main.c
*
* Description:
* Example 05 – ADC to PWM with UART Debug:
* Reads analog voltage from pin P6.0, maps it to a PWM duty cycle (on P5.0),
* and sends both values via UART using printf (retarget-io).
*
* Author: Rodrigo Rodrigues
*******************************************************************************/

#include "cybsp.h"                 // Board support package: handles pin, clock and peripheral setup
#include "cy_retarget_io.h"        // Retarget I/O library: allows printf to work with UART
#include "cycfg_peripherals.h"     // Includes peripheral configuration generated by Device Configurator

/*******************************************************************************
* Global Variables
*******************************************************************************/
volatile uint16_t AdcValue = 0;     // Holds the current ADC reading
uint16_t duty = 0;                  // PWM duty cycle value (mapped from ADC)

/*******************************************************************************
* Function: map
* Description: Maps a value from one range to another (e.g., from ADC to PWM)
* Parameters:
*   x        - input value
*   in_min   - minimum of input range
*   in_max   - maximum of input range
*   out_min  - minimum of output range
*   out_max  - maximum of output range
* Returns:
*   mapped output value as uint32_t
*******************************************************************************/
uint32_t map(uint32_t x, uint32_t in_min, uint32_t in_max, uint32_t out_min, uint32_t out_max)
{
    return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}

/*******************************************************************************
* Function Name: main
* Summary:
*   Initializes board, ADC, PWM, and UART. Continuously reads analog input,
*   maps it to PWM output, and prints values via serial terminal.
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    // Initialize board support (GPIO, clocks, etc.)
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0); // Stop execution if initialization fails
    }

    // Initialize UART with retarget-io for printf functionality
    cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE);

    // Clear terminal and print header
    printf("\x1b[2J\x1b[;H"); // ANSI escape codes to clear terminal
    printf("****************** Example 05 - ADC to PWM with UART ******************\r\n\n");

    // Initialize the ADC peripheral
    Cy_SAR2_Init(ADC_HW, &ADC_config);
    Cy_SAR2_SetReferenceBufferMode(PASS0_EPASS_MMIO, CY_SAR2_REF_BUF_MODE_OFF); // Optional: disable internal buffer
    Cy_SAR2_Channel_SoftwareTrigger(ADC_HW, 0); // Trigger first conversion on channel 0 (P6.0)

    // Initialize the PWM peripheral
    Cy_TCPWM_PWM_Init(PWM_0_HW, PWM_0_NUM, &PWM_0_config);
    Cy_TCPWM_PWM_Enable(PWM_0_HW, PWM_0_NUM);
    Cy_TCPWM_TriggerStart_Single(PWM_0_HW, PWM_0_NUM);

    // Enable global interrupts (not used here, but good practice)
    __enable_irq();

    // Main loop
    while (1)
    {
        // Read the ADC value from channel 0 (P6.0)
        AdcValue = Cy_SAR2_Channel_GetResult(ADC_HW, ADC_channel_0_IDX, NULL);

        // Map ADC value (0-4095) to PWM compare value (0-13110)
        duty = map(AdcValue, 0, 4095, 0, 13110);

        // Clamp PWM output range to safe limits
        if (duty <= 5)
        {
            duty = 0;
        }
        if (duty > 13100)
        {
            duty = 13111;
        }

        // Apply new PWM duty cycle
        Cy_TCPWM_PWM_SetCompare0(PWM_0_HW, PWM_0_NUM, duty);

        // Print values to terminal
        printf("ADC: %4d | PWM: %5d\r\n", AdcValue, duty);
    }
}

/* [] END OF FILE */
